apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: payment-ebs
reclaimPolicy: Retain
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer # storage will be created when pod is getting created

#kubectl apply -k "github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable/?ref=release-1.38"
# Node IAM- AmazonEBSCSIDriverPolicy, AmazonEC2FullAccess